### PR TITLE
Fixed issue #160 and some bugs in distributed streaming introduced after last PR

### LINKED ISSUE #160: Error in console from "mandatory" variable.
image
load the extension -> open the extension -> close -> open again and the error pops up on background console.

Error introduced in #157 some race condition is happening while setting state I think.

### PR DESCRIPTION
**Pull request by Lakshya2610**
Fixes #160

### CODE REVIEW

File: deployment/NetworkTree.js [hunk 1]
```diff
@@ -66,13 +66,15 @@ class NetworkTree {
      */
     removeNode(socket, socketID, room, root) {
         if(this.childNodes.length === 0) { return; }
-        this.childNodes.forEach((node) => {
-            if(node.socketID === socketID) {
-                this.notifyChildren(socket, node, room, root);
-            } else {
-                node.removeNode(socket, socketID, room, root);
+
```
Comment (alir128) [inline deployment/NetworkTree.js]: `this.childNodes.some((node) => {
            if(node.socketID === socketID) {
                this.notifyChildren(socket, node, room, root);
                return node.socketID === socketID;
            } else {
                node.removeNode(socket, socketID, room, root);
                return false
            }
            
        })`
can you switch this to something like this to remove the codacy issue.

Comment (Lakshya2610) [reply deployment/NetworkTree.js]: So, originally after the last PR when you switched it to forEach, the function stopped working. So I reverted it back. Let me see what I can do to fix codacy issues

Comment (alir128) [reply deployment/NetworkTree.js]: some function should work in this case
