### PR TITLE
Updated deployment with peer count fix

### LINKED ISSUE #172: report peer count back to host when using distributed streaming.
Currently only peers connected to the root node are reported as the grand children only report to their respective parent nodes.

### PR DESCRIPTION
**Pull request by Lakshya2610**
fixes #172 in deployment

### CODE REVIEW

File: deployment/server.js [hunk 1]
```diff
@@ -97,11 +97,10 @@ io.on("connection", (socket) => {
 
     const room = roomManager.getRoom(descData.room);
     if (room.room.addNode) {
-      room.room.addNode(
-        descData.id,
-        MAX_CLIENTS_PER_HOST,
-        descData.selectedHost
-      );
+
+      if(room.room.addNode(descData.id, MAX_CLIENTS_PER_HOST, descData.selectedHost)) {
```
Comment (ArsalaBangash) [inline deployment/server.js:101]: I took a look at the code. We should probably rename room.room to room.networkTree

File: deployment/server.js [hunk 2]
```diff
@@ -97,11 +97,10 @@ io.on("connection", (socket) => {
...
+        socket.to(descData.room).emit("incrementPeerCount");
```
Comment (alir128) [inline deployment/server.js:102]:
```suggestion
        io.sockets.socket(room.hostId).emit("incrementPeerCount")
```
or 
```suggestion
        io.to(room.hostId).emit("incrementPeerCount")
```

File: deployment/server.js [hunk 3]
```diff
@@ -115,6 +114,7 @@ io.on("connection", (socket) => {
     if (room) {
       if (room.room.removeNode) {
         room.room.removeNode(socket, req.socketID, req.room, room.room);
+        socket.to(req.room).emit("decrementPeerCount");
```
Comment (alir128) [inline deployment/server.js:117]: same as above, might be more secure instead of sending to the whole room.

Comment (Lakshya2610) [reply deployment/server.js:117]: Makes sense. Fixing it

File: deployment/server.js (hunk 1 above)
Comment (Lakshya2610) [reply deployment/server.js:101]: The reason it's called room is because it doesn't necessarily have to be a room with a tree. If it's a room without distributed  streaming, it doesn't make sense to call it NetworkTree. We can change it down the line when we completely move to the distributed system after it's reliable enough
